### ISSUE TITLE
Encounter Backward error during running example on pytorch by torch-directml

### ISSUE THREAD

**Issue by konas122** [MicrosoftDocs/windows-ai-docs#104]
My environment is PyTorch 1.13.1, torch-directml  0.1.13.1.dev230301

```
Traceback (most recent call last):
  File "D:/Program Files (x86)/PyCharm Community Edition 2022.2.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files (x86)\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Users\konas122\Program\PY\VPR\amd\amd_train.py", line 103, in <module>
    train(train_, test_, model2, loss, Device, writer, num_epochs, learn_rate, weight_decay)
  File "D:\Users\konas122\Program\PY\VPR\amd\amd_train.py", line 47, in train
    l.backward()
  File "D:\Anaconda\envs\d2l\lib\site-packages\torch\_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "D:\Anaconda\envs\d2l\lib\site-packages\torch\autograd\__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77b24029-8b4e-fa48-a11b-e0b93796d833
* Version Independent ID: 1026c5cb-f1ea-7f79-04ca-0a6e4c8a50f6
* Content: [Introduction to DirectML](https://learn.microsoft.com/en-us/windows/ai/directml/dml-intro)
* Content Source: [docs/directml/dml-intro.md](https://github.com/MicrosoftDocs/windows-ai-docs/blob/docs/docs/directml/dml-intro.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @konas122, I'll investigate.

**Comment by Adele101** [comment]
Hi @konas122 in order for our team to track this item correctly, could you please open an issue here? https://github.com/microsoft/DirectML/issues . Thanks!

**Comment by stevewhims** [comment]
Going ahead and closing, since it looks like there isn't a documentation issue to address in this case.

Thanks!
-Steve
